# Generated by Django 4.0.1 on 2022-01-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_address_options_alter_address_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProviderProfile',
            new_name='VendorProfile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_provider',
        ),
        migrations.AddField(
            model_name='user',
            name='is_vendor',
            field=models.BooleanField(default=False, verbose_name='Vendor status'),
        ),
    ]
