# Generated by Django 4.0.1 on 2022-04-13 20:25

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_address_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=1, upload_to=users.models.get_image_filename, verbose_name='Avatar'),
            preserve_default=False,
        ),
    ]
