# Generated by Django 4.0.1 on 2022-04-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_is_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reg_as_vendor',
            field=models.BooleanField(default=False, verbose_name='Registered as vendor'),
        ),
    ]
