# Generated by Django 4.0.1 on 2022-05-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_reg_as_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Agent Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='District Name'),
        ),
    ]
