# Generated by Django 4.0.1 on 2022-02-11 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='object_id',
            new_name='discount_object_id',
        ),
    ]
