# Generated by Django 4.0.1 on 2022-02-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaxUsesRule',
            new_name='UsageRule',
        ),
    ]
