# Generated by Django 4.0.1 on 2022-02-13 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promocoderule',
            name='allowed_brands',
            field=models.ManyToManyField(blank=True, help_text='If set to Null, it means general.', to='categories.Brand'),
        ),
        migrations.AddField(
            model_name='promocoderule',
            name='allowed_categories',
            field=models.ManyToManyField(blank=True, help_text='If set to Null, it means general.', to='categories.Category'),
        ),
        migrations.AddField(
            model_name='promocoderule',
            name='allowed_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_rule', to='gifts.allowedusersrule', verbose_name='Allowed users rule'),
        ),
        migrations.AddField(
            model_name='promocoderule',
            name='conditions',
            field=models.ManyToManyField(blank=True, help_text='If set to Null, it means general.', to='gifts.ConditionRule'),
        ),
        migrations.AddField(
            model_name='promocoderule',
            name='promo_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='gifts.promocode'),
        ),
        migrations.AddField(
            model_name='promocoderule',
            name='usage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_rule', to='gifts.usagerule', verbose_name='Max uses rule'),
        ),
        migrations.AddField(
            model_name='promocoderule',
            name='validity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_rule', to='gifts.validityrule', verbose_name='Validity rule'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='discount_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='allowedusersrule',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
