# Generated by Django 4.0.1 on 2022-02-11 12:41

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifts', '0002_rename_object_id_promocode_discount_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='maximum_usage',
            field=models.PositiveIntegerField(default=1, help_text='If set to 0, it means unlimited.'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='owners',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promocode',
            name='usage_limit_for_user',
            field=models.PositiveIntegerField(default=1, help_text='If set to 0, it means unlimited.'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='valid_from',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='promocode',
            name='valid_untill',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
