# Generated by Django 4.0.1 on 2022-02-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_rename_maxusesrule_usagerule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usagerule',
            options={'verbose_name': 'Usage Rule', 'verbose_name_plural': 'Usage Rules'},
        ),
        migrations.AlterField(
            model_name='validityrule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active?'),
        ),
    ]
