# Generated by Django 4.0.1 on 2022-02-11 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gifts', '0003_promocode_active_promocode_maximum_usage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='number_of_uses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code', to='contenttypes.contenttype'),
        ),
    ]
