# Generated by Django 4.0.1 on 2022-02-12 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('gifts', '0003_alter_usagerule_options_alter_validityrule_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocoderule',
            name='allowed_brands',
            field=models.ManyToManyField(blank=True, help_text='If set to Null, it means general.', to='categories.Brand'),
        ),
        migrations.AlterField(
            model_name='promocoderule',
            name='allowed_categories',
            field=models.ManyToManyField(blank=True, help_text='If set to Null, it means general.', to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='promocoderule',
            name='conditions',
            field=models.ManyToManyField(blank=True, help_text='If set to Null, it means general.', to='gifts.PromoCodeCondition'),
        ),
        migrations.AlterField(
            model_name='validityrule',
            name='valid_from',
            field=models.DateField(default=datetime.date.today, verbose_name='Valid from date'),
        ),
        migrations.AlterField(
            model_name='validityrule',
            name='valid_until',
            field=models.DateField(default=datetime.date.today, verbose_name='Expiration date'),
        ),
    ]
