# Generated by Django 4.0.1 on 2022-02-12 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0004_alter_promocoderule_allowed_brands_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PromoCodeCondition',
            new_name='ConditionRule',
        ),
    ]
