# Generated by Django 4.0.1 on 2022-02-12 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0005_rename_promocodecondition_conditionrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentagediscount',
            name='percentage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
