# Generated by Django 4.0.1 on 2022-02-11 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifts', '0006_alter_promocode_owners_redemption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='owners',
        ),
        migrations.AddField(
            model_name='promocode',
            name='owner',
            field=models.ForeignKey(help_text='If set to Null, it means general.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='promo_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='gifts.promocode'),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
