# Generated by Django 4.0.1 on 2022-02-12 17:44

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0006_alter_percentagediscount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentagediscount',
            name='max_discount_limit',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('100'), default_currency='SAR', help_text='If set to 0, it means Unlimited.', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(1)]),
        ),
    ]
