# Generated by Django 4.0.1 on 2022-02-11 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0008_promocodecondition_promocoderule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocodecondition',
            old_name='amount',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='promocodecondition',
            old_name='amount_currency',
            new_name='price_currency',
        ),
    ]
