# Generated by Django 4.0.1 on 2022-02-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0009_rename_amount_promocodecondition_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodecondition',
            name='operator',
            field=models.CharField(max_length=1),
        ),
    ]
