# Generated by Django 4.0.1 on 2022-01-17 11:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 1, 17, 11, 45, 11, 314285, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
