# Generated by Django 4.0.1 on 2022-02-18 17:43

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_feature_options_alter_featureoption_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendor', '0002_alter_stock_options_alter_stock_options_and_more'),
        ('payment', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='discount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=4, default=Decimal('0'), default_currency='SAR', max_digits=14, null=True, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='sub_total',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=4, default=Decimal('0'), default_currency='SAR', max_digits=14, null=True, verbose_name='Sub total'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='taxes',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), default_currency='SAR', max_digits=14, verbose_name='Taxes'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=4, default=Decimal('0'), default_currency='SAR', max_digits=14, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payment.cart', verbose_name='Cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.stock', verbose_name='Stock'),
        ),
    ]
