# Generated by Django 4.0.1 on 2022-01-30 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_feature_type'),
        ('payment', '0004_remove_cartitem_user_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='attributes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.featureattribute'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
