# Generated by Django 4.0.1 on 2022-01-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_feature_type'),
        ('payment', '0005_cartitem_attributes_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='attributes',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='attributes',
            field=models.ManyToManyField(null=True, to='products.FeatureAttribute'),
        ),
    ]
