# Generated by Django 4.0.1 on 2022-02-02 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('payment', '0006_order_creation_order_is_arrived_order_is_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.stock'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.stock'),
        ),
    ]
