# Generated by Django 4.0.1 on 2022-02-06 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_cartitem_stock_alter_orderitem_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='stock',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
