# Generated by Django 4.0.1 on 2022-01-31 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_featureattributesmap_quantity'),
        ('payment', '0008_remove_cart_items_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='attributes',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='attribute_map',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.featureattributesmap'),
            preserve_default=False,
        ),
    ]
