# Generated by Django 4.0.1 on 2022-01-31 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_remove_cartitem_attributes_cartitem_attribute_map'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='attribute_map',
            new_name='attributea_map',
        ),
    ]
