# Generated by Django 4.0.1 on 2022-01-31 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_rename_attribute_map_cartitem_attributea_map'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='attributea_map',
            new_name='attributes_map',
        ),
    ]
