# Generated by Django 4.0.1 on 2022-01-30 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_unique_together_category_brand_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'parent')},
        ),
        migrations.RemoveField(
            model_name='category',
            name='brand',
        ),
    ]
