# Generated by Django 4.0.1 on 2022-02-13 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('vendor', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vendor.stock'),
        ),
    ]
