# Generated by Django 4.0.1 on 2022-02-10 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0011_alter_favorite_products_alter_favorite_user'),
        ('users', '0003_remove_vendorprofile_user_delete_customerprofile_and_more'),
        ('vendor', '0003_remove_stock_attributes_stock_options'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vendor.stock'),
        ),
    ]
