# Generated by Django 4.0.1 on 2022-02-18 17:43

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_feature_options_alter_featureoption_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_address_options_alter_user_options_and_more'),
        ('vendor', '0002_alter_stock_options_alter_stock_options_and_more'),
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), default_currency='SAR', max_digits=14, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_arrived',
            field=models.BooleanField(default=False, verbose_name='Is arrived'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Is Cancelled'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_in_route',
            field=models.BooleanField(default=False, verbose_name='Is In Route'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is Paid'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_processed',
            field=models.BooleanField(default=True, verbose_name='Is Processed'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_shipped',
            field=models.BooleanField(default=False, verbose_name='Is Shipped'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sub_total',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default_currency='SAR', max_digits=14, verbose_name='Sub Total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='taxes',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), default_currency='SAR', max_digits=14, verbose_name='Taxes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default_currency='SAR', max_digits=14, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='orders.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vendor.stock', verbose_name='Stock'),
        ),
    ]
