# Generated by Django 4.0.1 on 2022-01-29 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productimage_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='provider',
            new_name='vendor',
        ),
    ]
