# Generated by Django 4.0.1 on 2022-02-17 16:25

from django.db import migrations, models
import src.utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-creation',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, default=src.utils.generate_random_string, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_cart_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
