# Generated by Django 4.0.1 on 2022-02-01 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='type',
        ),
    ]
