# Generated by Django 4.0.1 on 2022-01-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='type',
            field=models.CharField(default='GB', max_length=100),
            preserve_default=False,
        ),
    ]
