# Generated by Django 4.0.1 on 2022-02-18 17:43

import ckeditor_uploader.fields
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import djmoney.models.validators
import products.models
import src.utils


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_brand_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_alter_favorite_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
        migrations.AlterModelOptions(
            name='featureoption',
            options={'verbose_name': 'Feature Option', 'verbose_name_plural': 'Feature Options'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='products',
            field=models.ManyToManyField(to='products.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='featureoption',
            name='additional_price',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), default_currency='SAR', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Additional Price'),
        ),
        migrations.AlterField(
            model_name='featureoption',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.feature', verbose_name='Feature'),
        ),
        migrations.AlterField(
            model_name='featureoption',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='products', to='categories.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='products', to='categories.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, default=src.utils.generate_random_string, max_length=100, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(upload_to=products.models.get_image_filename, verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), default_currency='SAR', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_cart_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Minimun Cart Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('1'), default_currency='SAR', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(1)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Vendor'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(upload_to=products.models.get_image_filename, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(max_length=3000, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='review',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name='Dislikes'),
        ),
        migrations.AlterField(
            model_name='review',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
