# Generated by Django 4.0.1 on 2022-02-02 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_featureattribute_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='product',
        ),
    ]
