# Generated by Django 4.0.1 on 2022-01-31 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_featureattribute_additional_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureattributesmap',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='features_attributes_maps', to='products.product'),
            preserve_default=False,
        ),
    ]
