# Generated by Django 4.0.1 on 2022-02-02 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_stock_attributes_remove_stock_product'),
        ('payment', '0007_alter_cartitem_stock_alter_orderitem_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
