# Generated by Django 4.0.1 on 2022-01-16 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_review_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
