# Generated by Django 4.0.1 on 2022-01-31 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_featureattributesmap_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureattributesmap',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
