# Generated by Django 4.0.1 on 2022-05-30 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_offer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offer',
            new_name='OfferBanner',
        ),
    ]
