# Generated by Django 4.0.1 on 2022-01-16 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='body',
        ),
    ]
