# Generated by Django 4.0.1 on 2022-01-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_text_review_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data',
            field=models.JSONField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
