# Generated by Django 4.0.1 on 2022-02-07 18:09

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_delete_featureattribute_featureoption_feature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.ImageField(default='', upload_to=products.models.get_image_filename),
            preserve_default=False,
        ),
    ]
