# Generated by Django 4.0.1 on 2022-01-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_feature_featureattribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featureattribute',
            old_name='attribute',
            new_name='name',
        ),
    ]
