# Generated by Django 4.0.1 on 2022-01-16 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_attribute_featureattribute_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('attribute1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute1', to='products.featureattribute')),
                ('attribute2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute2', to='products.featureattribute')),
            ],
        ),
    ]
