# Generated by Django 4.0.1 on 2022-01-17 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_featuremap'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureattribute',
            name='dependent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.featureattribute'),
            preserve_default=False,
        ),
    ]
