# Generated by Django 4.0.1 on 2022-01-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_featureattribute_dependent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeatureMap',
        ),
    ]
