# Generated by Django 4.0.1 on 2022-01-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_delete_featuremap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='data',
        ),
    ]
