# Generated by Django 4.0.1 on 2022-01-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureattribute',
            name='dependent',
        ),
    ]
